---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-php-app
  labels:
    app: {{ template "fullname" . }}-php-app
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  selector:
    app: {{ template "fullname" . }}-php-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80