---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-player-blue-php
  labels:
    app: player-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player-php
  template:
    metadata:
      labels:
        app: player-php
        resetable: data
        team: blue
    spec:
      containers:
      - name: runner-php
        image: {{ .Values.imageName }}
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}-global-env
              key: APP_ENV
        - name: APP_TYPE
          value: player
        - name: APP_PLAYER_TEAM
          value: blue
        - name: APP_PLAYER_POSITION
          value: attack
        - name: APP_PLAYER_SKILL
          value: "1"

        ports:
        - name: nginx
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: nginx
          initialDelaySeconds: 10
          periodSeconds: 5
      volumeMounts:
      - mountPath: /tmpfs
        name: tmpfs
      volumes:
      - name: tmpfs
        emptyDir:
        medium: Memory
        sizeLimit: "10Mi"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-player-red-php
  labels:
    app: player-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player-php
  template:
    metadata:
      labels:
        app: player-php
        resetable: data
        team: red
    spec:
      containers:
      - name: runner-php
        image: {{ .Values.imageName }}
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}-global-env
              key: APP_ENV
        - name: APP_TYPE
          value: player
        - name: APP_PLAYER_TEAM
          value: red
        - name: APP_PLAYER_POSITION
          value: attack
        - name: APP_PLAYER_SKILL
          value: "2"
        ports:
        - name: nginx
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: nginx
          initialDelaySeconds: 10
          periodSeconds: 5
      volumeMounts:
      - mountPath: /tmpfs
        name: tmpfs
      volumes:
      - name: tmpfs
        emptyDir:
        medium: Memory
        sizeLimit: "10Mi"