---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-player-php
  labels:
    app: player-php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: player-php
  template:
    metadata:
      labels:
        app: player-php
    spec:
      containers:
      - name: runner-php
        image: {{ .Values.imageName }}
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}-global-env
              key: APP_ENV
        - name: APP_TYPE
          value: player
