---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-node
  labels:
    app: rabbitmq-node
spec:
  selector:
    app: rabbitmq-node
  ports:
    # the port that this service should serve on
    - port: 5672
      name: rabbitmq
      targetPort: 5672
