---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-rabbitmq-node
  labels:
    app: rabbitmq-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-node
  template:
    metadata:
      labels:
        app: rabbitmq-node
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.7.12-management
        # apt-get update && apt-get install -y vim bash
#        command:
#        - sh
#        args:
#        - "-c"
#        - sleep 10000
        ports:
          - name: http
            protocol: TCP
            containerPort: 15672
          - name: amqp
            protocol: TCP
            containerPort: 5672
#        livenessProbe:
#          exec:
#            command: ["rabbitmqctl", "status"]
#          initialDelaySeconds: 60
#          # See https://www.rabbitmq.com/monitoring.html for monitoring frequency recommendations.
#          periodSeconds: 60
#          timeoutSeconds: 15
#        readinessProbe:
#          exec:
#            command: ["rabbitmqctl", "status"]
#          initialDelaySeconds: 20
#          periodSeconds: 60
#          timeoutSeconds: 10
        env:
#          - name: MY_POD_IP
#            valueFrom:
#              fieldRef:
#                fieldPath: status.podIP
          #- name: POD_NAME
          #  value: "205672"
          - name: RABBITMQ_DIST_PORT
            value: "205672"
          #- name: RABBITMQ_USE_LONGNAME
          #  value: "true"
          #- name: K8S_SERVICE_NAME
          #  value: "rabbitmq"
          #- name: RABBITMQ_ERLANG_COOKIE
          #  value: "mycookie"
          - name: RABBITMQ_DEFAULT_USER
            value: admin
          - name: RABBITMQ_DEFAULT_PASS
            value: admin
          - name: RABBITMQ_NODENAME # this MUST be set to "[static-string]@localhost" in order for rabbitmq to properly load the persistent messages and queues, see also in top of the file
            value: rabbitmq@localhost

#        initContainers:
#          - name: configmap-copy
#            image: busybox
#            command: ['/bin/sh', '-c', 'cp /etc/rabbitmq/files/* /etc/rabbitmq/']
#            volumeMounts:
#              - name: config-volume
#                mountPath: /etc/rabbitmq/files
#              - name: config
#                mountPath: /etc/rabbitmq
#      volumes:
#        - name: config-volume
#          configMap:
#            name: rabbitmq-config
#            items:
#            - key: rabbitmq.conf
#              path: rabbitmq.conf
#            - key: enabled_plugins
#              path: enabled_plugins
