---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-stadium-php
  labels:
    app: stadium-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stadium-php
  template:
    metadata:
      labels:
        app: stadium-php
        resetable: data
    spec:
      containers:
      - name: runner-php
        containerPort: 8882
        image: {{ .Values.imageName }}
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}-global-env
              key: APP_ENV
        - name: APP_TYPE
          value: stadium
